### ISSUE TITLE
Output matches only the template and not the contents of the change

### ISSUE THREAD

**Issue by MrHinsh** [Ant0wan/openai-pr#31]
With the follwing configriation:

```
jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Ant0wan/openai-pr@v1
        with:
          api-key: ${{ secrets.OPENAI_API_KEY }}
          model: "gpt-3.5-turbo-instruct"
          template: |
            ## Description

            This pull request addresses the following issues:

            - Issue 1
            - Issue 2

            ## Changes

            - Change 1
            - Change 2
          header: "Based on the output of the command 'git diff', could you please generate a pull request description using the provided information? Be concise. Description must follow this format:"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

I get the following output:

```

## Description

This pull request addresses the following issues:

- Fixes issue with command output in git diff
- Implements changes requested in issue

## Changes

- Fixed command output
- Implemented requested changes
```

**This response is completely unrelated to the content of the change!**
